// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"ipc/ent/orders"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// Orders is the model entity for the Orders schema.
type Orders struct {
	config
	// ID of the ent.
	ID           int `json:"id,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Orders) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case orders.FieldID:
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Orders fields.
func (o *Orders) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case orders.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			o.ID = int(value.Int64)
		default:
			o.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Orders.
// This includes values selected through modifiers, order, etc.
func (o *Orders) Value(name string) (ent.Value, error) {
	return o.selectValues.Get(name)
}

// Update returns a builder for updating this Orders.
// Note that you need to call Orders.Unwrap() before calling this method if this Orders
// was returned from a transaction, and the transaction was committed or rolled back.
func (o *Orders) Update() *OrdersUpdateOne {
	return NewOrdersClient(o.config).UpdateOne(o)
}

// Unwrap unwraps the Orders entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (o *Orders) Unwrap() *Orders {
	_tx, ok := o.config.driver.(*txDriver)
	if !ok {
		panic("ent: Orders is not a transactional entity")
	}
	o.config.driver = _tx.drv
	return o
}

// String implements the fmt.Stringer.
func (o *Orders) String() string {
	var builder strings.Builder
	builder.WriteString("Orders(")
	builder.WriteString(fmt.Sprintf("id=%v", o.ID))
	builder.WriteByte(')')
	return builder.String()
}

// OrdersSlice is a parsable slice of Orders.
type OrdersSlice []*Orders
