// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"ipc/ent/otp"
	"ipc/ent/predicate"
	"ipc/ent/users"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// OtpUpdate is the builder for updating Otp entities.
type OtpUpdate struct {
	config
	hooks    []Hook
	mutation *OtpMutation
}

// Where appends a list predicates to the OtpUpdate builder.
func (ou *OtpUpdate) Where(ps ...predicate.Otp) *OtpUpdate {
	ou.mutation.Where(ps...)
	return ou
}

// SetCode sets the "code" field.
func (ou *OtpUpdate) SetCode(s string) *OtpUpdate {
	ou.mutation.SetCode(s)
	return ou
}

// SetNillableCode sets the "code" field if the given value is not nil.
func (ou *OtpUpdate) SetNillableCode(s *string) *OtpUpdate {
	if s != nil {
		ou.SetCode(*s)
	}
	return ou
}

// SetExpiresAt sets the "expires_at" field.
func (ou *OtpUpdate) SetExpiresAt(t time.Time) *OtpUpdate {
	ou.mutation.SetExpiresAt(t)
	return ou
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (ou *OtpUpdate) SetNillableExpiresAt(t *time.Time) *OtpUpdate {
	if t != nil {
		ou.SetExpiresAt(*t)
	}
	return ou
}

// SetUserID sets the "user_id" field.
func (ou *OtpUpdate) SetUserID(u uuid.UUID) *OtpUpdate {
	ou.mutation.SetUserID(u)
	return ou
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (ou *OtpUpdate) SetNillableUserID(u *uuid.UUID) *OtpUpdate {
	if u != nil {
		ou.SetUserID(*u)
	}
	return ou
}

// SetUsersID sets the "users" edge to the Users entity by ID.
func (ou *OtpUpdate) SetUsersID(id uuid.UUID) *OtpUpdate {
	ou.mutation.SetUsersID(id)
	return ou
}

// SetUsers sets the "users" edge to the Users entity.
func (ou *OtpUpdate) SetUsers(u *Users) *OtpUpdate {
	return ou.SetUsersID(u.ID)
}

// Mutation returns the OtpMutation object of the builder.
func (ou *OtpUpdate) Mutation() *OtpMutation {
	return ou.mutation
}

// ClearUsers clears the "users" edge to the Users entity.
func (ou *OtpUpdate) ClearUsers() *OtpUpdate {
	ou.mutation.ClearUsers()
	return ou
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (ou *OtpUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, ou.sqlSave, ou.mutation, ou.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (ou *OtpUpdate) SaveX(ctx context.Context) int {
	affected, err := ou.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (ou *OtpUpdate) Exec(ctx context.Context) error {
	_, err := ou.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ou *OtpUpdate) ExecX(ctx context.Context) {
	if err := ou.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ou *OtpUpdate) check() error {
	if v, ok := ou.mutation.Code(); ok {
		if err := otp.CodeValidator(v); err != nil {
			return &ValidationError{Name: "code", err: fmt.Errorf(`ent: validator failed for field "Otp.code": %w`, err)}
		}
	}
	if ou.mutation.UsersCleared() && len(ou.mutation.UsersIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Otp.users"`)
	}
	return nil
}

func (ou *OtpUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := ou.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(otp.Table, otp.Columns, sqlgraph.NewFieldSpec(otp.FieldID, field.TypeInt))
	if ps := ou.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := ou.mutation.Code(); ok {
		_spec.SetField(otp.FieldCode, field.TypeString, value)
	}
	if value, ok := ou.mutation.ExpiresAt(); ok {
		_spec.SetField(otp.FieldExpiresAt, field.TypeTime, value)
	}
	if ou.mutation.UsersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   otp.UsersTable,
			Columns: []string{otp.UsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(users.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ou.mutation.UsersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   otp.UsersTable,
			Columns: []string{otp.UsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(users.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, ou.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{otp.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	ou.mutation.done = true
	return n, nil
}

// OtpUpdateOne is the builder for updating a single Otp entity.
type OtpUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *OtpMutation
}

// SetCode sets the "code" field.
func (ouo *OtpUpdateOne) SetCode(s string) *OtpUpdateOne {
	ouo.mutation.SetCode(s)
	return ouo
}

// SetNillableCode sets the "code" field if the given value is not nil.
func (ouo *OtpUpdateOne) SetNillableCode(s *string) *OtpUpdateOne {
	if s != nil {
		ouo.SetCode(*s)
	}
	return ouo
}

// SetExpiresAt sets the "expires_at" field.
func (ouo *OtpUpdateOne) SetExpiresAt(t time.Time) *OtpUpdateOne {
	ouo.mutation.SetExpiresAt(t)
	return ouo
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (ouo *OtpUpdateOne) SetNillableExpiresAt(t *time.Time) *OtpUpdateOne {
	if t != nil {
		ouo.SetExpiresAt(*t)
	}
	return ouo
}

// SetUserID sets the "user_id" field.
func (ouo *OtpUpdateOne) SetUserID(u uuid.UUID) *OtpUpdateOne {
	ouo.mutation.SetUserID(u)
	return ouo
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (ouo *OtpUpdateOne) SetNillableUserID(u *uuid.UUID) *OtpUpdateOne {
	if u != nil {
		ouo.SetUserID(*u)
	}
	return ouo
}

// SetUsersID sets the "users" edge to the Users entity by ID.
func (ouo *OtpUpdateOne) SetUsersID(id uuid.UUID) *OtpUpdateOne {
	ouo.mutation.SetUsersID(id)
	return ouo
}

// SetUsers sets the "users" edge to the Users entity.
func (ouo *OtpUpdateOne) SetUsers(u *Users) *OtpUpdateOne {
	return ouo.SetUsersID(u.ID)
}

// Mutation returns the OtpMutation object of the builder.
func (ouo *OtpUpdateOne) Mutation() *OtpMutation {
	return ouo.mutation
}

// ClearUsers clears the "users" edge to the Users entity.
func (ouo *OtpUpdateOne) ClearUsers() *OtpUpdateOne {
	ouo.mutation.ClearUsers()
	return ouo
}

// Where appends a list predicates to the OtpUpdate builder.
func (ouo *OtpUpdateOne) Where(ps ...predicate.Otp) *OtpUpdateOne {
	ouo.mutation.Where(ps...)
	return ouo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (ouo *OtpUpdateOne) Select(field string, fields ...string) *OtpUpdateOne {
	ouo.fields = append([]string{field}, fields...)
	return ouo
}

// Save executes the query and returns the updated Otp entity.
func (ouo *OtpUpdateOne) Save(ctx context.Context) (*Otp, error) {
	return withHooks(ctx, ouo.sqlSave, ouo.mutation, ouo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (ouo *OtpUpdateOne) SaveX(ctx context.Context) *Otp {
	node, err := ouo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (ouo *OtpUpdateOne) Exec(ctx context.Context) error {
	_, err := ouo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ouo *OtpUpdateOne) ExecX(ctx context.Context) {
	if err := ouo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ouo *OtpUpdateOne) check() error {
	if v, ok := ouo.mutation.Code(); ok {
		if err := otp.CodeValidator(v); err != nil {
			return &ValidationError{Name: "code", err: fmt.Errorf(`ent: validator failed for field "Otp.code": %w`, err)}
		}
	}
	if ouo.mutation.UsersCleared() && len(ouo.mutation.UsersIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Otp.users"`)
	}
	return nil
}

func (ouo *OtpUpdateOne) sqlSave(ctx context.Context) (_node *Otp, err error) {
	if err := ouo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(otp.Table, otp.Columns, sqlgraph.NewFieldSpec(otp.FieldID, field.TypeInt))
	id, ok := ouo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Otp.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := ouo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, otp.FieldID)
		for _, f := range fields {
			if !otp.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != otp.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := ouo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := ouo.mutation.Code(); ok {
		_spec.SetField(otp.FieldCode, field.TypeString, value)
	}
	if value, ok := ouo.mutation.ExpiresAt(); ok {
		_spec.SetField(otp.FieldExpiresAt, field.TypeTime, value)
	}
	if ouo.mutation.UsersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   otp.UsersTable,
			Columns: []string{otp.UsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(users.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ouo.mutation.UsersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   otp.UsersTable,
			Columns: []string{otp.UsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(users.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Otp{config: ouo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, ouo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{otp.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	ouo.mutation.done = true
	return _node, nil
}
