// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"ipc/ent/otp"
	"ipc/ent/users"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// OtpCreate is the builder for creating a Otp entity.
type OtpCreate struct {
	config
	mutation *OtpMutation
	hooks    []Hook
}

// SetCode sets the "code" field.
func (oc *OtpCreate) SetCode(s string) *OtpCreate {
	oc.mutation.SetCode(s)
	return oc
}

// SetExpiresAt sets the "expires_at" field.
func (oc *OtpCreate) SetExpiresAt(t time.Time) *OtpCreate {
	oc.mutation.SetExpiresAt(t)
	return oc
}

// SetUserID sets the "user_id" field.
func (oc *OtpCreate) SetUserID(u uuid.UUID) *OtpCreate {
	oc.mutation.SetUserID(u)
	return oc
}

// SetUsersID sets the "users" edge to the Users entity by ID.
func (oc *OtpCreate) SetUsersID(id uuid.UUID) *OtpCreate {
	oc.mutation.SetUsersID(id)
	return oc
}

// SetUsers sets the "users" edge to the Users entity.
func (oc *OtpCreate) SetUsers(u *Users) *OtpCreate {
	return oc.SetUsersID(u.ID)
}

// Mutation returns the OtpMutation object of the builder.
func (oc *OtpCreate) Mutation() *OtpMutation {
	return oc.mutation
}

// Save creates the Otp in the database.
func (oc *OtpCreate) Save(ctx context.Context) (*Otp, error) {
	return withHooks(ctx, oc.sqlSave, oc.mutation, oc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (oc *OtpCreate) SaveX(ctx context.Context) *Otp {
	v, err := oc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (oc *OtpCreate) Exec(ctx context.Context) error {
	_, err := oc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (oc *OtpCreate) ExecX(ctx context.Context) {
	if err := oc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (oc *OtpCreate) check() error {
	if _, ok := oc.mutation.Code(); !ok {
		return &ValidationError{Name: "code", err: errors.New(`ent: missing required field "Otp.code"`)}
	}
	if v, ok := oc.mutation.Code(); ok {
		if err := otp.CodeValidator(v); err != nil {
			return &ValidationError{Name: "code", err: fmt.Errorf(`ent: validator failed for field "Otp.code": %w`, err)}
		}
	}
	if _, ok := oc.mutation.ExpiresAt(); !ok {
		return &ValidationError{Name: "expires_at", err: errors.New(`ent: missing required field "Otp.expires_at"`)}
	}
	if _, ok := oc.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "Otp.user_id"`)}
	}
	if len(oc.mutation.UsersIDs()) == 0 {
		return &ValidationError{Name: "users", err: errors.New(`ent: missing required edge "Otp.users"`)}
	}
	return nil
}

func (oc *OtpCreate) sqlSave(ctx context.Context) (*Otp, error) {
	if err := oc.check(); err != nil {
		return nil, err
	}
	_node, _spec := oc.createSpec()
	if err := sqlgraph.CreateNode(ctx, oc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	oc.mutation.id = &_node.ID
	oc.mutation.done = true
	return _node, nil
}

func (oc *OtpCreate) createSpec() (*Otp, *sqlgraph.CreateSpec) {
	var (
		_node = &Otp{config: oc.config}
		_spec = sqlgraph.NewCreateSpec(otp.Table, sqlgraph.NewFieldSpec(otp.FieldID, field.TypeInt))
	)
	if value, ok := oc.mutation.Code(); ok {
		_spec.SetField(otp.FieldCode, field.TypeString, value)
		_node.Code = value
	}
	if value, ok := oc.mutation.ExpiresAt(); ok {
		_spec.SetField(otp.FieldExpiresAt, field.TypeTime, value)
		_node.ExpiresAt = value
	}
	if nodes := oc.mutation.UsersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   otp.UsersTable,
			Columns: []string{otp.UsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(users.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OtpCreateBulk is the builder for creating many Otp entities in bulk.
type OtpCreateBulk struct {
	config
	err      error
	builders []*OtpCreate
}

// Save creates the Otp entities in the database.
func (ocb *OtpCreateBulk) Save(ctx context.Context) ([]*Otp, error) {
	if ocb.err != nil {
		return nil, ocb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(ocb.builders))
	nodes := make([]*Otp, len(ocb.builders))
	mutators := make([]Mutator, len(ocb.builders))
	for i := range ocb.builders {
		func(i int, root context.Context) {
			builder := ocb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*OtpMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, ocb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, ocb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, ocb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (ocb *OtpCreateBulk) SaveX(ctx context.Context) []*Otp {
	v, err := ocb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ocb *OtpCreateBulk) Exec(ctx context.Context) error {
	_, err := ocb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ocb *OtpCreateBulk) ExecX(ctx context.Context) {
	if err := ocb.Exec(ctx); err != nil {
		panic(err)
	}
}
