// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"ipc/ent/trades"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// Trades is the model entity for the Trades schema.
type Trades struct {
	config
	// ID of the ent.
	ID           int `json:"id,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Trades) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case trades.FieldID:
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Trades fields.
func (t *Trades) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case trades.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			t.ID = int(value.Int64)
		default:
			t.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Trades.
// This includes values selected through modifiers, order, etc.
func (t *Trades) Value(name string) (ent.Value, error) {
	return t.selectValues.Get(name)
}

// Update returns a builder for updating this Trades.
// Note that you need to call Trades.Unwrap() before calling this method if this Trades
// was returned from a transaction, and the transaction was committed or rolled back.
func (t *Trades) Update() *TradesUpdateOne {
	return NewTradesClient(t.config).UpdateOne(t)
}

// Unwrap unwraps the Trades entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (t *Trades) Unwrap() *Trades {
	_tx, ok := t.config.driver.(*txDriver)
	if !ok {
		panic("ent: Trades is not a transactional entity")
	}
	t.config.driver = _tx.drv
	return t
}

// String implements the fmt.Stringer.
func (t *Trades) String() string {
	var builder strings.Builder
	builder.WriteString("Trades(")
	builder.WriteString(fmt.Sprintf("id=%v", t.ID))
	builder.WriteByte(')')
	return builder.String()
}

// TradesSlice is a parsable slice of Trades.
type TradesSlice []*Trades
