// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Orders is the predicate function for orders builders.
type Orders func(*sql.Selector)

// Otp is the predicate function for otp builders.
type Otp func(*sql.Selector)

// Trades is the predicate function for trades builders.
type Trades func(*sql.Selector)

// Users is the predicate function for users builders.
type Users func(*sql.Selector)
