version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/ipc_db
      - ENV=development
    volumes:
      # Mount source code for hot-reload if you implement it
      - ../:/app
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - ipc-network

  postgres:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ipc_db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - ipc-network

volumes:
  postgres-data:

networks:
  ipc-network:
    driver: bridge